import numpy as np

#write a function to create a linear system given a set of normal vector and particular solution

def top_down(normal_vectors, particular_vec):
    coefficient_matrix = np.array(normal_vectors)
    augmented_column = np.inner(coefficient_matrix, particular_vec)
    
    return coefficient_matrix, augmented_column

### VERIFICATION ############################
aug_matrix = lambda A,B : np.array([np.concatenate((A[i],B.reshape(len(A),-1)[i])) for i in range(len(A))])

#top-down affine set generated by set of normal vectors and a particular vector
normal = np.array([[1,-1,0],[2,0,-3],[0,2,1]])
particular = np.array([8,2,0])
print(aug_matrix(normal,top_down(normal,particular)[1]),"\n")